export interface User {
    id: number;
    avatar: string;
    firstName: string;
    lastName: string;
    email: string;
    phone: string;
    role: "Student" | "Teacher" | "Admin" | "Staff";
    isStaff: boolean;
    status: "Active" | "Inactive";
  }
  
  export const usersData: User[] = [
    {
      id: 1,
      avatar: "https://i.pravatar.cc/150?img=1",
      firstName: "Rahul",
      lastName: "Sharma",
      email: "rahul.sharma@school.com",
      phone: "9876543210",
      role: "Student",
      isStaff: false,
      status: "Active",
    },
    {
      id: 2,
      avatar: "https://i.pravatar.cc/150?img=2",
      firstName: "Anita",
      lastName: "Verma",
      email: "anita.verma@school.com",
      phone: "9876501234",
      role: "Teacher",
      isStaff: true,
      status: "Active",
    },
    {
      id: 3,
      avatar: "https://i.pravatar.cc/150?img=3",
      firstName: "Suresh",
      lastName: "Patil",
      email: "suresh.patil@school.com",
      phone: "9988776655",
      role: "Admin",
      isStaff: true,
      status: "Active",
    },
    {
      id: 4,
      avatar: "https://i.pravatar.cc/150?img=4",
      firstName: "Pooja",
      lastName: "Nair",
      email: "pooja.nair@school.com",
      phone: "9123456789",
      role: "Student",
      isStaff: false,
      status: "Inactive",
    },
    {
      id: 5,
      avatar: "https://i.pravatar.cc/150?img=5",
      firstName: "Amit",
      lastName: "Kumar",
      email: "amit.kumar@school.com",
      phone: "9012345678",
      role: "Teacher",
      isStaff: true,
      status: "Active",
    },
    {
      id: 6,
      avatar: "https://i.pravatar.cc/150?img=6",
      firstName: "Neha",
      lastName: "Singh",
      email: "neha.singh@school.com",
      phone: "8899776655",
      role: "Staff",
      isStaff: true,
      status: "Active",
    },
    {
      id: 7,
      avatar: "https://i.pravatar.cc/150?img=7",
      firstName: "Rohit",
      lastName: "Mehta",
      email: "rohit.mehta@school.com",
      phone: "9988123456",
      role: "Student",
      isStaff: false,
      status: "Active",
    },
    {
      id: 8,
      avatar: "https://i.pravatar.cc/150?img=8",
      firstName: "Kavita",
      lastName: "Iyer",
      email: "kavita.iyer@school.com",
      phone: "9090909090",
      role: "Teacher",
      isStaff: true,
      status: "Inactive",
    },
    {
      id: 9,
      avatar: "https://i.pravatar.cc/150?img=9",
      firstName: "Vikram",
      lastName: "Reddy",
      email: "vikram.reddy@school.com",
      phone: "9445566778",
      role: "Admin",
      isStaff: true,
      status: "Active",
    },
    {
      id: 10,
      avatar: "https://i.pravatar.cc/150?img=10",
      firstName: "Sneha",
      lastName: "Joshi",
      email: "sneha.joshi@school.com",
      phone: "9332211445",
      role: "Student",
      isStaff: false,
      status: "Active",
    },
    {
      id: 11,
      avatar: "https://i.pravatar.cc/150?img=11",
      firstName: "Arjun",
      lastName: "Kapoor",
      email: "arjun.kapoor@school.com",
      phone: "9877012345",
      role: "Student",
      isStaff: false,
      status: "Inactive",
    },
    {
      id: 12,
      avatar: "https://i.pravatar.cc/150?img=12",
      firstName: "Meena",
      lastName: "Gupta",
      email: "meena.gupta@school.com",
      phone: "9123098765",
      role: "Staff",
      isStaff: true,
      status: "Active",
    },
    {
      id: 13,
      avatar: "https://i.pravatar.cc/150?img=13",
      firstName: "Sanjay",
      lastName: "Mishra",
      email: "sanjay.mishra@school.com",
      phone: "9887766554",
      role: "Teacher",
      isStaff: true,
      status: "Active",
    },
    {
      id: 14,
      avatar: "https://i.pravatar.cc/150?img=14",
      firstName: "Divya",
      lastName: "Chopra",
      email: "divya.chopra@school.com",
      phone: "9554433221",
      role: "Student",
      isStaff: false,
      status: "Active",
    },
    {
      id: 15,
      avatar: "https://i.pravatar.cc/150?img=15",
      firstName: "Nitin",
      lastName: "Agarwal",
      email: "nitin.agarwal@school.com",
      phone: "9876001122",
      role: "Admin",
      isStaff: true,
      status: "Inactive",
    },
    {
      id: 16,
      avatar: "https://i.pravatar.cc/150?img=16",
      firstName: "Rina",
      lastName: "Das",
      email: "rina.das@school.com",
      phone: "9001122334",
      role: "Teacher",
      isStaff: true,
      status: "Active",
    },
    {
      id: 17,
      avatar: "https://i.pravatar.cc/150?img=17",
      firstName: "Kunal",
      lastName: "Bansal",
      email: "kunal.bansal@school.com",
      phone: "9888997766",
      role: "Student",
      isStaff: false,
      status: "Active",
    },
    {
      id: 18,
      avatar: "https://i.pravatar.cc/150?img=18",
      firstName: "Alok",
      lastName: "Tripathi",
      email: "alok.tripathi@school.com",
      phone: "9776655443",
      role: "Staff",
      isStaff: true,
      status: "Active",
    },
    {
      id: 19,
      avatar: "https://i.pravatar.cc/150?img=19",
      firstName: "Pallavi",
      lastName: "Kulkarni",
      email: "pallavi.kulkarni@school.com",
      phone: "9888001122",
      role: "Teacher",
      isStaff: true,
      status: "Inactive",
    },
    {
      id: 20,
      avatar: "https://i.pravatar.cc/150?img=20",
      firstName: "Manoj",
      lastName: "Yadav",
      email: "manoj.yadav@school.com",
      phone: "9112233445",
      role: "Student",
      isStaff: false,
      status: "Active",
    },
  ];
  